# Generated by Django 4.2.1 on 2023-07-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtickets',
            name='quantity',
        ),
    ]
